import yaml
from pathlib import Path

print("🚀 Phase 3: Expanding Light Speed Holdings + Building Validator...")

# 1. Expanded company-registry.yaml
with open('company-registry.yaml', 'w', encoding='utf-8') as f:
    f.write("""company:
  name: Light Speed Holdings
  ceo: human_operator
  agents:
    - id: chief_of_staff
      name: Chief of Staff
      title: Chief of Staff
      description: The primary orchestrator and strategic alignment agent for the entire company.
      department: Executive
      reports_to: human_operator
      direct_reports: [cto, coo, caio, cfo]
      responsibilities:
        - Align company goals across all departments.
        - Orchestrate agent communication and task delegation.
        - Monitor operational bottlenecks and resolve cross-department conflicts.
        - Serve as the primary interface between the human CEO and the agent workforce.
      guidelines: Maintain high-level strategic oversight. Never execute low-level tasks directly; always delegate to the appropriate executive or department head. Escalate blockers to the human operator only when autonomous resolution fails.
      tools: [read, write, execute, delegate]

    - id: cto
      name: Chief Technology Officer
      title: CTO
      description: Oversees all technological infrastructure, software architecture, and engineering teams.
      department: Technology
      reports_to: chief_of_staff
      direct_reports: [lead_backend, lead_frontend, devops_lead]
      responsibilities:
        - Architect robust, scalable AI agent systems.
        - Review and approve code generated by development agents.
        - Ensure system security, reliability, and performance.
        - Define the technical roadmap and engineering standards.
      guidelines: Prioritize clean, maintainable, and well-tested code. Enforce strict version control practices. All architecture decisions must be documented.
      tools: [read, write, execute, code_interpreter]

    - id: coo
      name: Chief Operating Officer
      title: COO
      description: Manages day-to-day operations, internal processes, and workflow optimization.
      department: Operations
      reports_to: chief_of_staff
      direct_reports: [hr_lead, ops_analyst]
      responsibilities:
        - Optimize internal workflows and eliminate redundancies.
        - Manage agent resource allocation and task scheduling.
        - Track KPIs and operational metrics across departments.
      guidelines: Focus on efficiency, process automation, and measurable outcomes. Every process should have a documented SOP.
      tools: [read, write, execute]

    - id: caio
      name: Chief AI Officer
      title: CAIO
      description: Directs AI research, model selection, prompt engineering, and agent capability development.
      department: AI Research
      reports_to: chief_of_staff
      direct_reports: [ml_engineer, prompt_engineer]
      responsibilities:
        - Evaluate and integrate new LLM models and APIs.
        - Fine-tune prompts and agent system instructions for maximum efficacy.
        - Research emerging AI capabilities and assess their business value.
        - Design agent evaluation benchmarks and quality assurance protocols.
      guidelines: Stay at the cutting edge of AI advancements. Every model integration must include a cost-benefit analysis. Prioritize practical application over theoretical exploration.
      tools: [read, write, execute, web_search]

    - id: cfo
      name: Chief Financial Officer
      title: CFO
      description: Manages budgets, API cost tracking, and financial forecasting for agent operations.
      department: Finance
      reports_to: chief_of_staff
      direct_reports: [finance_analyst]
      responsibilities:
        - Track and optimize API token usage and compute costs.
        - Forecast operational budgets based on agent activity projections.
        - Generate financial reports on ROI of agent deployments.
      guidelines: Maintain strict cost discipline. Flag any agent or workflow that exceeds its allocated budget threshold.
      tools: [read, write, execute]

    - id: lead_backend
      name: Lead Backend Engineer
      title: Lead Backend Engineer
      description: Manages backend systems, APIs, and server-side agent logic.
      department: Technology
      reports_to: cto
      direct_reports: []
      responsibilities:
        - Develop and maintain REST APIs and agent communication endpoints.
        - Implement database schemas for agent memory and state management.
      guidelines: Write modular, well-documented code with comprehensive test coverage.
      tools: [read, write, execute, code_interpreter]

    - id: ml_engineer
      name: ML Engineer
      title: ML Engineer
      description: Implements machine learning pipelines and model integrations.
      department: AI Research
      reports_to: caio
      direct_reports: []
      responsibilities:
        - Build and deploy ML pipelines for agent evaluation.
        - Fine-tune models on company-specific datasets.
      guidelines: Document all experiments with reproducible configurations.
      tools: [read, write, execute, code_interpreter]

    - id: prompt_engineer
      name: Prompt Engineer
      title: Prompt Engineer
      description: Crafts and optimizes agent system prompts and behavioral instructions.
      department: AI Research
      reports_to: caio
      direct_reports: []
      responsibilities:
        - Design structured prompts that maximize agent reliability.
        - A/B test prompt variations and measure performance deltas.
      guidelines: Every prompt change must be version-controlled and accompanied by evaluation metrics.
      tools: [read, write, execute]
""")
print("✅ Expanded company-registry.yaml with 8 agents across 4 departments")

# 2. Create the Dependency Validator
with open('src/ai_company/validator.py', 'w', encoding='utf-8') as f:
    f.write("""import yaml
from pathlib import Path

class CompanyValidator:
    def __init__(self, registry_path="company-registry.yaml"):
        self.registry_path = Path(registry_path)
        self.errors = []
        self.warnings = []

    def load_registry(self):
        with open(self.registry_path, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)

    def validate(self):
        data = self.load_registry()
        agents = data.get('company', {}).get('agents', [])
        ceo = data.get('company', {}).get('ceo', 'human_operator')

        agent_ids = {a['id'] for a in agents}
        agent_map = {a['id']: a for a in agents}

        print(f"Validating {len(agents)} agents...")

        for agent in agents:
            aid = agent['id']

            # Check required fields
            for field in ['id', 'name', 'title', 'department', 'reports_to']:
                if field not in agent or not agent[field]:
                    self.errors.append(f"[{aid}] Missing required field: {field}")

            # Check reports_to exists
            reports_to = agent.get('reports_to', '')
            if reports_to != ceo and reports_to not in agent_ids:
                self.errors.append(f"[{aid}] reports_to '{reports_to}' does not exist in registry")

            # Check direct_reports exist
            for report_id in agent.get('direct_reports', []):
                if report_id not in agent_ids:
                    self.errors.append(f"[{aid}] direct_report '{report_id}' does not exist in registry")

            # Check for self-reporting
            if reports_to == aid:
                self.errors.append(f"[{aid}] Agent cannot report to itself")

        # Check for circular dependencies
        self._check_circular_deps(agent_map, ceo)

        # Print results
        if self.warnings:
            print(f"\\n⚠️  {len(self.warnings)} Warning(s):")
            for w in self.warnings:
                print(f"   {w}")

        if self.errors:
            print(f"\\n❌ {len(self.errors)} Error(s):")
            for e in self.errors:
                print(f"   {e}")
            return False
        else:
            print("\\n✅ Company structure is valid! No errors found.")
            return True

    def _check_circular_deps(self, agent_map, ceo):
        for start_id in agent_map:
            visited = set()
            current = start_id
            while current and current != ceo:
                if current in visited:
                    self.errors.append(f"Circular dependency detected involving: {start_id}")
                    break
                visited.add(current)
                current = agent_map.get(current, {}).get('reports_to', '')
""")
print("✅ Created src/ai_company/validator.py")

# 3. Update cli.py to include the validate command
with open('src/ai_company/cli.py', 'w', encoding='utf-8') as f:
    f.write("""import click
from ai_company.generator import AgentGenerator
from ai_company.validator import CompanyValidator

@click.group()
def cli():
    \"\"\"Light Speed Holdings AI Company Builder CLI.\"\"\"
    pass

@cli.command()
def generate():
    \"\"\"Generate all OpenCode agent files from the registry.\"\"\"
    generator = AgentGenerator()
    generator.generate_all()

@cli.command()
def validate():
    \"\"\"Validate the company registry for structural integrity.\"\"\"
    validator = CompanyValidator()
    success = validator.validate()
    if not success:
        raise SystemExit(1)

if __name__ == '__main__':
    cli()
""")
print("✅ Updated src/ai_company/cli.py with validate command")

print("\\n🎯 Phase 3 setup complete!")
