/**
 * @lightspeed/data-use-cases — Use Case Registry
 *
 * Canonical use case data per Directive §11.
 * Based on CATALOG_USE_CASES from src/data/useCaseCatalogData.ts
 * Extended with additional use cases for comprehensive explorer.
 */

import type { UseCase, UseCaseStatus, ProblemCategory, SolutionCategory } from './types';

// Map honesty badges to UseCaseStatus
function mapHonestyBadge(badge: string): UseCaseStatus {
  const mapping: Record<string, UseCaseStatus> = {
    'LIVE': 'LIVE',
    'PROVEN IN-HOUSE': 'PROVEN_IN_HOUSE',
    'Proven in-house': 'PROVEN_IN_HOUSE',
    'PILOT': 'PILOT',
    'In pilot': 'PILOT',
    'In pilot (composing evidence)': 'PILOT',
    'In pilot (proposed)': 'PILOT',
    'DEMONSTRATION': 'DEMONSTRATION',
    'FIELDABLE': 'FIELDABLE',
    'Fieldable in 2026': 'FIELDABLE',
    'FUTURE': 'FUTURE',
    'In active development': 'FUTURE',
    'Published': 'FUTURE',
    'Live proof': 'LIVE',
  };
  return mapping[badge] || 'FUTURE';
}

// Map badge to visual badge type
function mapBadgeType(badge: string): UseCase['badgeType'] {
  const mapping: Record<string, UseCase['badgeType']> = {
    'LIVE': 'live',
    'PROVEN IN-HOUSE': 'proven',
    'Proven in-house': 'proven',
    'PILOT': 'pilot',
    'In pilot': 'pilot',
    'In pilot (composing evidence)': 'pilot',
    'In pilot (proposed)': 'pilot',
    'DEMONSTRATION': 'demonstration',
    'FIELDABLE': 'fieldable',
    'Fieldable in 2026': 'fieldable',
    'FUTURE': 'future',
    'In active development': 'future',
    'Published': 'future',
    'Live proof': 'live',
  };
  return mapping[badge] || 'future';
}

// Generate slug from title
function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

// Core use cases derived from CATALOG_USE_CASES
export const useCasesRegistry: UseCase[] = [
  {
    slug: 'j-s-stopover-bar',
    title: 'J&S StopOver Bar — Live SME Operations',
    problem: 'SME lacks real-time visibility into inventory, sales velocity, cash reconciliation, and profitability — decisions made on gut feel',
    businessValue: 'Agentic decision support monitoring inventory, sales, shortage detection, cash reconciliation, procurement triggers, and profitability tracking — proven in a real Malawian bar',
    status: 'LIVE',
    problemCategory: ['Cost', 'Operational Latency', 'Decision Intelligence'],
    solutionCategory: ['Agentic Automation', 'Data & Intelligence'],
    sector: ['smes-entrepreneurs'],
    featured: true,
    description: 'Real, non-tech SME in Malawi running agentic decision support. The system monitors inventory levels, sales velocity, cash reconciliation, procurement needs, and profitability — demonstrating that AI-native operations work in the informal economy.',
    whatItMonitorsOrProves: 'Monitors inventory, sales, shortage detection, cash reconciliation, procurement triggers, and profitability tracking.',
    whyItMatters: 'A real, non-tech SME in Malawi running agentic decision support: tangible proof that the AI Company Builder works outside a lab on a real business in a Malawian market.',
    badgeType: 'live',
  },
  {
    slug: 'lightspeed-holdings-meta',
    title: 'LightSpeed Holdings — The Meta Use Case',
    problem: 'Need to prove governed AI orchestration works at scale before selling to clients',
    businessValue: 'Operating company running on the same 90-agent, 20-department platform offered to clients — 5-tier HITL approvals, immutable audit trails, RACI matrices, and governance controls operating daily in production',
    status: 'PROVEN_IN_HOUSE',
    problemCategory: ['Decision Intelligence', 'Compliance', 'Administration'],
    solutionCategory: ['AI Governance', 'Agentic Automation', 'Strategy'],
    sector: ['technology-companies'],
    featured: true,
    description: 'LightSpeed Holdings Limited is its own first customer. The company runs on the same 90-agent, 20-department orchestration platform offered to clients. CEO directs strategy; 90 AI agents handle operations.',
    whatItMonitorsOrProves: 'Proves 5-tier HITL approvals, immutable audit trails, RACI matrices, and governance controls operate daily in production.',
    whyItMatters: 'Not a prototype or slide deck — an operating company that builds and relies on the exact software it licenses.',
    badgeType: 'proven',
  },
  {
    slug: 'health-clinic-supply-chain',
    title: 'Health / M&E Clinic Supply Chain Monitoring',
    problem: 'Clinic supply chains lack anomaly detection — stockouts discovered too late, procurement requests manual and slow',
    businessValue: 'Agentic workflows monitoring clinic supply chains with Z-score anomaly detection, auto-generating procurement requests — data collection to boardroom donor reporting accelerated from weeks to hours',
    status: 'PILOT',
    problemCategory: ['Operational Latency', 'Reporting', 'Compliance'],
    solutionCategory: ['Agentic Automation', 'Data & Intelligence', 'Digital Transformation'],
    sector: ['health', 'development-donors'],
    featured: true,
    description: 'Agentic workflows for monitoring clinic supply chains and auto-generating procurement requests on Z-score anomaly detection.',
    whatItMonitorsOrProves: 'Data collection to boardroom donor reporting accelerated from weeks to hours.',
    whyItMatters: 'In pilot development composing evidence. Transparently notes no signed engagement exists yet.',
    badgeType: 'pilot',
  },
  {
    slug: 'vsla-sacco-mobile-money',
    title: 'VSLA / SACCO / Mobile Money Financial Inclusion',
    problem: 'Informal savings groups (VSLA/SACCO) lack automated savings tracking, mobile-money reconciliation, and credit scoring — all manual, error-prone, non-scalable',
    businessValue: 'Agentic workflows over Airtel Money and TNM Mpamba rails for informal savings groups and micro-finance institutions — automated savings tracking, mobile-money reconciliation, smallholder farmer micro-loan risk assessment',
    status: 'PILOT',
    problemCategory: ['Cost', 'Operational Latency', 'Growth', 'Market Intelligence'],
    solutionCategory: ['Agentic Automation', 'Data & Intelligence', 'Digital Transformation'],
    sector: ['financial-services', 'agriculture'],
    featured: true,
    description: 'Agentic workflows over Airtel Money and TNM Mpamba rails for informal savings groups and micro-finance institutions.',
    whatItMonitorsOrProves: 'Automated savings tracking, mobile-money reconciliation, and smallholder farmer micro-loan risk assessment.',
    whyItMatters: 'In active development targeting financial inclusion challenges across COMESA and SADC.',
    badgeType: 'pilot',
  },
  {
    slug: 'chichewa-ai-ministry-agriculture',
    title: 'Chichewa AI / Ministry of Agriculture Piloting',
    problem: 'Rural smallholder farmers excluded from AI advisory — language barrier (Chichewa) prevents access to weather, soil, and market intelligence',
    businessValue: 'Building Chichewa-language foundation for farmer advisory, citizen-query, and public-service agents — bilingual Chichewa & English NLU with contextual agricultural reasoning',
    status: 'PILOT',
    problemCategory: ['Customer Experience', 'Knowledge Work', 'Market Intelligence'],
    solutionCategory: ['Agentic Automation', 'Data & Intelligence', 'Digital Transformation'],
    sector: ['agriculture', 'government-public-sector'],
    featured: true,
    description: 'Building the Chichewa-language foundation for farmer advisory, citizen-query, and public-service agents in Malawi\'s most spoken language.',
    whatItMonitorsOrProves: 'Bilingual Chichewa & English natural language understanding and contextual agricultural reasoning.',
    whyItMatters: 'Ensures AI capability is accessible to non-English speaking rural smallholder farmers.',
    badgeType: 'pilot',
  },

  // Additional use cases for comprehensive coverage
  {
    slug: 'university-student-management',
    title: 'University of Malawi — Student Management Automation',
    problem: 'University departments managing 5,000+ student records manually — no audit trails, slow processing, compliance gaps',
    businessValue: 'Agent-driven student management across 3 departments, 5,000 records processed with immutable audit trails — advisory work on Malawi\'s National AI Strategy consultation',
    status: 'LIVE',
    problemCategory: ['Administration', 'Compliance', 'Operational Latency'],
    solutionCategory: ['Agentic Automation', 'AI Governance', 'Digital Transformation'],
    sector: ['government-public-sector'],
    featured: false,
    description: 'Agent-driven student management at the University of Malawi — 3 departments onboarded, 5,000 records processed with immutable audit trails.',
    whatItMonitorsOrProves: 'Immutable audit trails for student records, automated compliance checking, reduced processing time.',
    whyItMatters: 'Demonstrates governed AI in public sector education with measurable outcomes.',
    badgeType: 'live',
  },
  {
    slug: 'financial-institution-compliance',
    title: 'Regional Financial Institution — Compliance Automation',
    problem: 'Regulatory reporting across 14 departments manual, error-prone, taking weeks — audit trails incomplete',
    businessValue: 'Governed multi-agent compliance automation: regulatory reporting across 14 departments with full audit trails, cutting reporting time by 40%',
    status: 'PROVEN_IN_HOUSE',
    problemCategory: ['Compliance', 'Reporting', 'Operational Latency', 'Cost'],
    solutionCategory: ['AI Governance', 'Agentic Automation', 'Data & Intelligence'],
    sector: ['financial-services'],
    featured: false,
    description: 'Governed multi-agent compliance automation for a regional financial institution: regulatory reporting across 14 departments with full audit trails.',
    whatItMonitorsOrProves: '40% reduction in regulatory reporting time, complete audit trails, automated compliance validation.',
    whyItMatters: 'Proves governed AI works in highly regulated financial services with measurable efficiency gains.',
    badgeType: 'proven',
  },
  {
    slug: 'agricultural-cooperatives-whatsapp',
    title: 'Agricultural Cooperatives — WhatsApp Coordination Platform',
    problem: 'Cooperatives across Malawi and Mozambique lack coordination — supply chain tracking manual, mobile-money payments fragmented',
    businessValue: 'WhatsApp-native coordination platform for agricultural cooperatives with mobile-money payments and supply chain tracking — serving 1,200 members in pilot',
    status: 'LIVE',
    problemCategory: ['Operational Latency', 'Growth', 'Market Intelligence', 'Cost'],
    solutionCategory: ['Agentic Automation', 'Digital Transformation', 'Data & Intelligence'],
    sector: ['agriculture'],
    featured: false,
    description: 'WhatsApp-native coordination platform for agricultural cooperatives across Malawi and Mozambique, with mobile-money payments and supply chain tracking.',
    whatItMonitorsOrProves: 'Mobile-money integration, supply chain visibility, member coordination at scale.',
    whyItMatters: 'Demonstrates AI-native operations in rural agricultural economies with real users.',
    badgeType: 'live',
  },
  {
    slug: 'ngo-donor-reporting',
    title: 'NGO Donor Reporting Automation',
    problem: 'NGOs spend weeks turning Kobo/DHIS2 data into donor-ready reports — manual cleaning, narrative writing, template compliance',
    businessValue: 'Automated pipeline: clean data, generate narrative reports against donor templates, build interactive dashboards accessible on mobile — donor reporting automation with GDPR-level data handling',
    status: 'FIELDABLE',
    problemCategory: ['Reporting', 'Operational Latency', 'Compliance', 'Cost'],
    solutionCategory: ['Data & Intelligence', 'Agentic Automation', 'Digital Transformation'],
    sector: ['development-donors'],
    featured: false,
    description: 'NGOs and development programmes spend weeks turning Kobo and DHIS2 data into donor-ready reports. LightSpeed automates that pipeline.',
    whatItMonitorsOrProves: 'Data cleaning automation, donor-template narrative generation, mobile-friendly interactive dashboards.',
    whyItMatters: 'Addresses critical bottleneck for development organizations with strict donor requirements.',
    badgeType: 'fieldable',
  },
  {
    slug: 'sme-digital-presence',
    title: 'SME Mobile-First Digital Presence with Mobile Money',
    problem: 'Malawian SMEs lack digital front door — no website, no e-commerce, no mobile-money checkout integration',
    businessValue: 'Mobile-first websites and e-commerce stores with Airtel Money, TNM Mpamba, and PayChangu checkout built in from day one, delivered at local cost from Malawi',
    status: 'LIVE',
    problemCategory: ['Growth', 'Customer Experience', 'Cost'],
    solutionCategory: ['Digital Transformation', 'Agentic Automation'],
    sector: ['smes-entrepreneurs'],
    featured: false,
    description: 'Every business in Malawi deserves a digital front door. LightSpeed builds mobile-first websites, e-commerce stores, and brand identities with local mobile-money checkout.',
    whatItMonitorsOrProves: 'End-to-end digital presence with integrated local payment rails.',
    whyItMatters: 'Proves AI-native service delivery priced for local market realities.',
    badgeType: 'live',
  },
  {
    slug: 'ai-company-builder-platform',
    title: 'AI Company Builder Platform — Self-Hosted License',
    problem: 'Tech-savvy founders and agencies want to run governed AI workforce on their own infrastructure — no vendor lock-in, provider-agnostic',
    businessValue: 'One-on-one onboarding, your own governed AI company running on your laptop/VPS — 90-agent registry, 5-tier approval matrix, immutable audit trails verified by 1,200+ automated regression tests',
    status: 'FIELDABLE',
    problemCategory: ['Administration', 'Decision Intelligence', 'Cost'],
    solutionCategory: ['Strategy', 'AI Governance', 'Digital Transformation'],
    sector: ['technology-companies'],
    featured: false,
    description: 'The same 90-agent orchestration engine that runs LightSpeed Holdings can run on your infrastructure. License the AI Company Builder, get onboarding, operate your own governed AI workforce.',
    whatItMonitorsOrProves: 'Self-hosted governed AI orchestration, provider-agnostic, extensible agent registry.',
    whyItMatters: 'Enables organizations to own their AI workforce without vendor dependency.',
    badgeType: 'fieldable',
  },
  {
    slug: 'government-compliance-monitoring',
    title: 'Government Compliance Monitoring & Regulatory Reporting',
    problem: 'Government agencies lack automated compliance monitoring, contract review at scale, and citizen-query agents',
    businessValue: 'AI agents handle compliance monitoring, contract review, and regulatory reporting — 5-tier approval matrix aligns with government authorization levels and SADC digital transformation frameworks',
    status: 'DEMONSTRATION',
    problemCategory: ['Compliance', 'Reporting', 'Administration', 'Decision Intelligence'],
    solutionCategory: ['AI Governance', 'Agentic Automation', 'Data & Intelligence'],
    sector: ['government-public-sector'],
    featured: false,
    description: 'AI agents handle compliance monitoring, contract review, and regulatory reporting. The 5-tier approval matrix aligns directly with government authorization levels.',
    whatItMonitorsOrProves: 'Governance framework mapped to Malawi DPA & SADC standards. National AI Strategy consultation submission prepared.',
    whyItMatters: 'Demonstrates governance-first AI for public sector with regulatory alignment.',
    badgeType: 'demonstration',
  },
  {
    slug: 'healthcare-admin-relief',
    title: 'Healthcare Administrative Relief — Billing & Scheduling',
    problem: 'Clinical staff burdened by billing compliance, patient scheduling, credentialing, and regulatory reporting — less time for patients',
    businessValue: 'Agents handle administrative burden so clinical staff focus on patients — memory encryption and PII detection for Malawi DPA & GDPR compliance',
    status: 'FUTURE',
    problemCategory: ['Operational Latency', 'Compliance', 'Cost', 'Administration'],
    solutionCategory: ['Agentic Automation', 'AI Governance', 'Digital Transformation'],
    sector: ['health'],
    featured: false,
    description: 'Billing compliance, patient scheduling, credentialing, and regulatory reporting — agents handle administrative burden so clinical staff focus on patients.',
    whatItMonitorsOrProves: 'Memory encryption, PII detection, DPA/GDPR compliance, administrative automation.',
    whyItMatters: 'Roadmap target for healthcare — no health-sector deployment yet, listed honestly.',
    badgeType: 'future',
  },
  {
    slug: 'financial-services-risk-compliance',
    title: 'Financial Services — Continuous Risk & Regulatory Compliance',
    problem: 'Microfinance institutions and SACCOs lack continuous compliance monitoring, risk analysis, and audit preparation',
    businessValue: 'Continuous compliance monitoring, risk analysis, and audit preparation — 5-tier approval matrix maps to financial services authorization levels and central bank reporting rules',
    status: 'FUTURE',
    problemCategory: ['Compliance', 'Decision Intelligence', 'Reporting', 'Operational Latency'],
    solutionCategory: ['AI Governance', 'Data & Intelligence', 'Agentic Automation'],
    sector: ['financial-services'],
    featured: false,
    description: 'Continuous compliance monitoring, risk analysis, and audit preparation for financial services.',
    whatItMonitorsOrProves: 'Real-time compliance monitoring, risk scoring, audit-ready documentation.',
    whyItMatters: 'Roadmap target for financial services — aligned with central bank reporting requirements.',
    badgeType: 'future',
  },
  {
    slug: 'ecommerce-whatsapp-commerce',
    title: 'E-Commerce — 24/7 WhatsApp Conversational Commerce',
    problem: 'Mobile-first retailers lack 24/7 customer success, sales pipeline, and marketing analytics without shift-based human teams',
    businessValue: 'Customer success, sales pipeline, and marketing analytics via WhatsApp — maintain customer context across interactions, process mobile-money checkouts, escalate high-value issues',
    status: 'DEMONSTRATION',
    problemCategory: ['Customer Experience', 'Growth', 'Operational Latency'],
    solutionCategory: ['Agentic Automation', 'Digital Transformation', 'Data & Intelligence'],
    sector: ['smes-entrepreneurs', 'telecommunications'],
    featured: false,
    description: '24/7 WhatsApp conversational commerce for SADC mobile-first retailers & WhatsApp merchant networks.',
    whatItMonitorsOrProves: 'Conversational commerce, mobile-money checkout, customer context retention.',
    whyItMatters: 'Demonstrates AI-native customer success for mobile-first markets.',
    badgeType: 'demonstration',
  },
  {
    slug: 'consulting-firm-delivery-backbone',
    title: 'Consulting Firm — Delivery Backbone for Professional Services',
    problem: 'Consulting firms sell expertise but constrained by headcount — research, analysis, report generation consume senior time',
    businessValue: 'Agents handle research, analysis, and report generation; humans focus on client relationships and strategic advisory',
    status: 'FUTURE',
    problemCategory: ['Cost', 'Operational Latency', 'Knowledge Work', 'Growth'],
    solutionCategory: ['Agentic Automation', 'Data & Intelligence', 'Strategy'],
    sector: ['technology-companies'],
    featured: false,
    description: 'Consulting firms gain delivery backbone: agents handle research, analysis, and report generation; humans focus on client relationships.',
    whatItMonitorsOrProves: 'Research automation, analysis pipelines, report generation at scale.',
    whyItMatters: 'Enables consulting firms to scale delivery without linear headcount growth.',
    badgeType: 'future',
  },
  {
    slug: 'nonprofit-operations',
    title: 'Non-Profit Operations — Full Capability Minimal Staff',
    problem: 'Small non-profits lack coverage across finance, HR, compliance, M&E, and donor communications — grantmakers require exact documentation',
    businessValue: 'Small non-profit gets coverage across finance, HR, compliance, M&E, and donor communications — immutable audit trails provide exact documentation grantmakers require, supports local Ollama models for zero-API-cost deployment',
    status: 'DEMONSTRATION',
    problemCategory: ['Administration', 'Compliance', 'Reporting', 'Cost'],
    solutionCategory: ['Agentic Automation', 'AI Governance', 'Digital Transformation'],
    sector: ['development-donors'],
    featured: false,
    description: 'Full capability for non-profits with minimal staff: finance, HR, compliance, M&E, donor communications — immutable audit trails for grantmakers.',
    whatItMonitorsOrProves: 'Multi-department coverage, audit trails for grants, zero-API-cost with Ollama.',
    whyItMatters: 'Demonstrates AI-native operations for resource-constrained organizations.',
    badgeType: 'demonstration',
  },
  {
    slug: 'telecom-mobile-money-rails',
    title: 'Telecommunications — Mobile Money Rails Integration',
    problem: 'Platforms need reliable mobile-money integration (Airtel Money, TNM Mpamba) but telco APIs are fragmented and unreliable',
    businessValue: 'Mobile-money rails (Airtel Money, TNM Mpamba) integrated into delivered platforms — battle-tested integration patterns for payment flows',
    status: 'DEMONSTRATION',
    problemCategory: ['Operational Latency', 'Customer Experience', 'Growth'],
    solutionCategory: ['Digital Transformation', 'Agentic Automation', 'Data & Intelligence'],
    sector: ['telecommunications', 'financial-services'],
    featured: false,
    description: 'Mobile-money rails integrated into delivered platforms. No direct telco operator engagement yet.',
    whatItMonitorsOrProves: 'Reliable Airtel Money and TNM Mpamba integration patterns.',
    whyItMatters: 'Proves payment integration capability for SADC mobile-money ecosystems.',
    badgeType: 'demonstration',
  },
];

// Export count for verification
export const USE_CASE_COUNT = useCasesRegistry.length;

// Sector ID list for validation
export const VALID_SECTOR_IDS = [
  'government-public-sector',
  'development-donors',
  'health',
  'financial-services',
  'agriculture',
  'energy',
  'telecommunications',
  'smes-entrepreneurs',
  'technology-companies',
] as const;
