"""Compute SRI (Subresource Integrity) hashes for CDN dependencies.

Usage:
    python scripts/compute_sri.py

Downloads each pinned CDN library, computes the SHA-384 hash, and prints
the ``integrity`` attribute value ready for pasting into ``<script>`` or
``<link>`` tags.

This script is part of PRE-15 / DASH-008 (SRI hashes for CDN assets).
Run it before each production deployment to refresh hashes after any
version bump.

Requirements: Python 3.11+, no external packages (uses stdlib only).
"""

from __future__ import annotations

import base64
import hashlib
import sys
import urllib.request

# ── Pinned CDN dependencies ─────────────────────────────────────────

CDN_ASSETS: list[tuple[str, str]] = [
    (
        "Tailwind CSS",
        "https://cdn.tailwindcss.com",
    ),
    (
        "Alpine.js",
        "https://cdn.jsdelivr.net/npm/alpinejs@3.14.9/dist/cdn.min.js",
    ),
    (
        "Chart.js",
        "https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js",
    ),
]


def compute_sri(url: str) -> str:
    """Download *url* and return its ``sha384-...`` SRI hash."""
    try:
        with urllib.request.urlopen(url, timeout=15) as resp:
            data = resp.read()
    except Exception as exc:
        return f"ERROR: {exc}"

    digest = hashlib.sha384(data).digest()
    encoded = base64.b64encode(digest).decode("ascii")
    return f"sha384-{encoded}"


def main() -> None:
    print("<!-- SRI hashes — generated by scripts/compute_sri.py -->")
    print("<!-- Paste the integrity= values into templates/base.html -->")
    print()

    for name, url in CDN_ASSETS:
        sri = compute_sri(url)
        print(f"<!-- {name} -->")
        print(f"<!-- URL: {url} -->")
        print(f'<!-- integrity="{sri}" crossorigin="anonymous" -->')
        print()

    if any(sri.startswith("ERROR") for _, _ in CDN_ASSETS):
        sys.exit(1)


if __name__ == "__main__":
    main()
